### ISSUE TITLE
0 is converted to null

### ISSUE THREAD

**Issue by smartens80** [omatech/laravel-bulk-importer#2]
A csv column value of 0 (zero) is converted to null in insert statement.

Fix below: -

![image](https://user-images.githubusercontent.com/18694052/175202538-65893f75-fce1-4ff8-b890-2ca5bf2df5e7.png)

**Comment by smartens80** [comment]
Update: Should be `!=` instead of `!==` so it can handle '0' as a string.

**Comment by aponscat** [comment]
Thanks a lot for using the package and reporting the issue.

I've created a new release with the fixed issue.
